<?xml version='1.0' encoding='utf-8' ?>
<!DOCTYPE students SYSTEM "student1.dtd">
<!--<!DOCTYPE students [-->
<!--        <!ELEMENT students (student*)>-->
<!--        <!ELEMENT student (name,age,sex)>-->
<!--        <!ELEMENT name (#PCDATA)>-->
<!--        <!ELEMENT age (#PCDATA)>-->
<!--        <!ELEMENT sex (#PCDATA)>-->
<!--        <!ATTLIST student number ID #REQUIRED>-->
<!--        ]>-->
<!--<!DOCTYPE students PUBLIC "student1.dtd" "网络路径url">-->
<students>
    <student number="1001">
        <name id="1">zhangsan</name>
        <age>18</age>
        <sex>male</sex>
    </student>
    <student number="1002">
        <name>lisi</name>
        <age>20</age>
        <sex>female</sex>
    </student>
    <student number="1003">
        <name>wangwu</name>
        <age>24</age>
        <sex>male</sex>
    </student>
</students>